# 5. 데이터 전처리 (Data Preprocessing)

<br>

**결손값 처리**

- 사이킷런의 ML 알고리즘은 결손값(NaN, Null)을 허용하지 않음
- 이러한 Null 값은 고정된 다른 값으로 변환해야 한다.

**Null 값 처리 방법**

- 피처 값 중 Null 값이 얼마 되지 않는다.  
$\Rightarrow$ 피처의 평균값 등으로 간단히 대체  
  
  
- 피처 값 중 Null 값이 대부분이다.  
$\Rightarrow$ 해당 피처는 드롭하는 것이 더 좋다.  
  
  
- 피처 값 중 Null 값이 일정 수준 이상 되는 경우
  - 일정 수준 이상의 기준은 없다.
  - 해당 피처가 중요도가 높은 피처이고 Null을 단순히 피처의 평균값으로 대체할 경우 예측 왜곡이 심할 수 있는 경우  
  $\Rightarrow$ 업무 로직 등을 상세히 검토해 더 정밀한 대체 값을 선정

**문자열 값**

- 사이킷런의 머신러닝 알고리즘은 문자열 값을 입력값으로 허용하지 않는다.  
$\Rightarrow$ 모든 문자열 값은 인코딩돼서 숫자 형으로 변환해야 한다.

**문자열 피처**

- 카테고리형 피처
  - 코드 값으로 표현하는 게 더 이해하기 쉬움  
  
  
- 텍스트형 피처
  - 피처 벡터화(feature vectorization) 등의 기법으로 벡터화  
  ('텍스트 분석' 장에서 별도로 설명)
  - 불필요한 피처라고 판단되면 삭제

**식별자 피처**

- ex) 주민번호, 단순 문자열 아이디
- 인코딩하지 않고 삭제하는 게 더 좋다.
- 이러한 식별자 피처는 단순히 데이터 로우를 식별하는 용도로 사용됨
- 예측에 중요한 요소가 될 수는 없음
- 알고리즘을 오히려 복잡하게 만들고 예측 성능을 떨어뜨림

<br>

## 5.1 데이터 인코딩

**데이터 인코딩의 종류**

1. 레이블 인코딩 (Label encoding)
2. 원-핫 인코딩 (One Hot encoding)

<br>

### 5.1.1 레이블 인코딩 (Label encoding)

카테고리 피처를 코드형 숫자 값으로 변환한다.  
사이킷런의 레이블 인코딩은 `LabelEncoder` 클래스로 구현한다.  
`LabelEncoder`를 객체로 생성한 후 `fit()`과 `transform()`을 호출해 레이블 인코딩을 수행

In [1]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


<br>

`LabelEncoder.classes_`

- 문자열 값이 어떤 숫자 값으로 인코딩됐는 지를 알 수 있다.
- 0번부터 순서대로 변환된 인코딩 값에 대한 원본 값을 가지고 있다.

In [2]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


<br>

`LabelEncoder.inverse_transform()`

- 인코딩된 값을 다시 디코딩할 수 있다.

In [3]:
print('디코딩 원본 값:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


C:\Users\shkim\AppData\Local\conda\conda\envs\TF_VS_36\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


<br>

**레이블 인코딩의 한계**

- 간단하게 문자열 값을 숫자형 카테고리 값으로 변환
- 하지만 일괄적인 숫자 값으로 변환이 되면서 몇몇 ML 알고리즘에는 이를 적용할 경우 예측 성능이 떨어질 수 있다.
  - 숫자 값의 경우 **크고 작음에 대한 특성이 작용**하기 때문
  - 숫자 값이 큰 경우 특정 ML 알고리즘에서 가중치가 더 부여되거나 더 중요하게 인식할 가능성이 발생  
  
  
- 레이블 인코딩을 적용하면 안되는 ML 알고리즘
  - 선형 회귀  
  
  
- 레이블 인코딩을 적용해도 괜찮은 ML 알고리즘
  - 트리 계열 알고리즘 (숫자의 이러한 특성을 반영하지 않음)

<br>

### 5.1.2 원-핫 인코딩 (Ont-Hot Encoding)

- 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 컬럼에만 1을 표시하고 나머지 컬럼에는 0을 표시하는 방식
- 행 형태로 돼 있는 피처의 고유 값  
$\rightarrow$ 열 형태로 차원을 변환  
$\rightarrow$ 고유 값에 해당하는 컬럼에만 1을 표시  
$\rightarrow$ 나머지 컬럼에는 0을 표시
- 이러한 특성으로 원-핫(여러 개의 속성 중 단 한 개의 속성만 1로 표시) 인코딩으로 명명하게 됨

<br>

**원-핫 인코딩 방법 (2가지)**

1. `OneHotEncoder`  
2. `pd.get_dummies()`

<br>

`preprocessing.OneHotEncoder`

`OneHotEncoder` 사용 시 주의 사항
1. `OneHotEncoder`로 변환하기 전에 모든 문자열 값이 숫자형 값으로 변환돼야 한다.
2. 입력 값으로 2차원 데이터가 필요하다.


In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 1. 먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2. 2차원 데이터로 변환
labels = labels.reshape(-1, 1)

# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


<br>

`pd.get_dummies()`

판다스에서 원-핫 인코딩을 더 쉽게 지원하는 API.  
사이킷런의 `OneHotEncoder`와 다르게 문자열 카테고리 값을 숫자형으로 변환할 필요 없이 바로 변환 가능

In [8]:
import pandas as pd

df = pd.DataFrame({'item': ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

<br>

## 5.2 피처 스케일링과 정규화

**피처 스케일링 (feature scaling)**

- 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 방법
- 대표적인 방법
  1. 표준화 (Standardization)
  2. 정규화 (Normalization)

**표준화 (Strandardization)**

- 데이터의 피처 각각이 평균이 0이고 분산이 1인 가우시안 정규 분포를 가진 값으로 변환  
  
  
- 표준화를 통해 변환될 피처 $x$의 새로운 $i$번째 데이터 = ${x_i}\_new$
- 이 값은 원래 값에서 피처 $x$의 평균을 뺀 값을 피처 $x$의 표준편차로 나눈 값으로 계산  

$$
{x_i}\_new = {x_i - mean(x) \over stdev(x)}
$$ 

**정규화 (Normalization)**

- 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 개념
- 예)
  - 피처 A : 거리를 나타내는 변수 (0 ~ 100KM)
  - 피처 B : 금액을 나타내는 속성 (0 ~ 100,000,000,000원)
  - 이 변수를 모두 동일한 크기 단위로 비교하기 위해 값을 모두 최소 0 ~ 최대 1의 값으로 변환하는 것
  - 개별 데이터의 크기를 모두 똑같은 단위로 변경하는 것  
  
  
- 새로운 데이터 ${x_i}\_new$는 원래 값에서 피처 $x$의 최솟값을 뺀 값을 피처 $x$의 최댓값과 최솟값의 차이로 나눈 값으로 변환  
  
  
$$
{x_i}\_new = {x_i - min(x) \over max(x) - min(x)}
$$

**`Normalizer` 모듈과 일반적인 정규화의 차이점**

사이킷런의 전처리에서 제공하는 `Normalizer` 모듈과 일반적인 정규화는 약간의 차이가 있다. (큰 개념은 동일)  
  
  
사이킷런의 `Normalizer` 모듈은 선형대수에서의 정규화 개념이 적용.  
개별 벡터의 크기를 맞추기 위해 변환하는 것을 의미  
즉, 개별 벡터를 모든 피처 벡터의 크기로 나눠줌
  
  
세 개의 피처 $x$, $y$, $z$가 있다고 하면 새로운 데이터 ${x_i}\_new$는 원래 값에서 세 개의 피처의 $i$번째 피처 값에 해당하는 크기를 합한 값으로 나눠준다.

$$
{x_i}\_new = {x_i \over \sqrt{{x_i}^2 + {y_i}^2  + {z_i}^2}}
$$

일반적인 의미의 표준화와 정규화 $\Rightarrow$ **피처 스케일링**으로 통칭  
선형대수 개념의 정규화 $\Rightarrow$ **벡터 정규화**로 지칭

<br>

**사이킷런이 제공하는 대표적인 피처 스케일링 클래스**

`StandardScaler`  
`MinMaxScaler`

<br>

### 5.2.1 `StandardScaler`

**표준화**를 쉽게 지원하기 위한 클래스.  
개별 피처를 평균이 0이고, 분산이 1인 값으로 변환.  

**가우시안 정규 분포를 가질 수 있도록 데이터를 변환하는 것이 중요한 알고리즘**

사이킷런에서 구현한 `RBF` 커널을 이용하는 알고리즘
- 서포트 벡터 머신 (Support Vector Machine)
- 선형 회귀 (Linear Regression)
- 로지스틱 회귀 (Logistic Regression)

위 알고리즘들은 데이터가 가우시안 분포를 가지고 있다고 가정.  
사전에 표준화를 적용하는 것은 예측 성능 향상에 중요한 요소가 될 수 있다.

In [11]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 세트를 로딩하고 DataFrame으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.054000
petal length (cm)    3.758667
petal width (cm)     1.198667
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.188004
petal length (cm)    3.113179
petal width (cm)     0.582414
dtype: float64


In [12]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler 로 데이터 세트 변환
# - fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 NumPy ndarray로 반환됨
# 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.637024e-15
petal length (cm)   -1.482518e-15
petal width (cm)    -1.623146e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


<br>

### 5.2.2 `MinMaxScaler`

데이터값을 0과 1사이의 범위 값으로 변환.  
음수 값이 있으면 -1에서 1값으로 변환.  
데이터의 분포가 가우시안 분포가 아닐 경우에 Min, Max Scale을 적용해 볼 수 있다.

In [13]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler로 데이터 세트 변환
# - fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 NumPy ndarray로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
